<?php

namespace site7\studio\services;

use Craft;
use craft\base\Component;
use craft\elements\db\ElementQueryInterface;
use craft\elements\Entry;
use craft\fields\Assets;
use craft\helpers\FileHelper;
use craft\helpers\StringHelper;
use craft\web\UploadedFile;
use site7\studio\services\import\MatrixEntryTypeImportService;
use site7\studio\services\support\AssetCaptureHelper;
use site7\studio\Site7Studio;
use site7\studio\records\PackageRecord;
use Symfony\Component\Yaml\Yaml;

/**
 * Generates a new Template package from the current content of an existing entry's
 * Site7 Matrix field ("Save as Template").
 */
class TemplateGeneratorService extends Component
{
    /**
     * @param Entry $entry The saved entry to generate a Template from.
     * @param array $meta {name, description, category, tags, previewImage?: UploadedFile}
     * @return PackageRecord The newly registered Template package.
     * @throws \Exception if the entry has no content in the configured Matrix field.
     */
    public function generateFromEntry(Entry $entry, array $meta): PackageRecord
    {
        $matrixHandle = $this->getMatrixFieldHandle();
        if (!$matrixHandle) {
            throw new \Exception('No Site7 Matrix field is configured.');
        }

        // Blocks inserted via this plugin's own Section/Pattern/Template insert flow
        // can remain provisional drafts on the owner until a subsequent native
        // full-page save merges them, so the default (canonical-only) field-value
        // query can under-report; read inclusively of drafts here.
        $fieldValue = $entry->getFieldValue($matrixHandle);
        $blocks = $fieldValue ? $fieldValue->status(null)->drafts(null)->savedDraftsOnly(false)->all() : [];
        if (empty($blocks)) {
            throw new \Exception('This entry has no Site7 content to save as a Template.');
        }

        $entryTypeToSection = $this->buildEntryTypeToSectionMap();

        // packagePath is created up front (rather than after content
        // extraction, as before) so extractFieldValues() below can copy any
        // captured Assets field's file(s) directly into it - see
        // AssetCaptureHelper::captureAssetField().
        $handle = $this->generateUniqueHandle($meta['name']);
        $packagePath = rtrim(Craft::getAlias('@packages'), '/') . '/' . $handle;
        FileHelper::createDirectory($packagePath);

        try {
            return $this->buildAndRegisterPackage($entry, $meta, $matrixHandle, $blocks, $entryTypeToSection, $handle, $packagePath);
        } catch (\Throwable $e) {
            // Never leave a half-written package directory behind on
            // failure (e.g. "no recognized Site7 Sections") - packagePath is
            // now created up front (needed so Assets capture can copy files
            // into it), so a failure partway through must clean up after
            // itself the same way the old "create the directory only after
            // everything succeeded" order used to guarantee for free.
            FileHelper::removeDirectory($packagePath);
            throw $e;
        }
    }

    /**
     * @param Entry[] $blocks
     * @param array<string, string> $entryTypeToSection
     */
    private function buildAndRegisterPackage(Entry $entry, array $meta, string $matrixHandle, array $blocks, array $entryTypeToSection, string $handle, string $packagePath): PackageRecord
    {
        // Extract, in order: [sectionHandle => demoContent] pairs. A block
        // whose Entry Type isn't yet a recognized Site7 Section package is no
        // longer silently dropped - a Section package is generated on the fly
        // from that live Entry Type (reusing MatrixEntryTypeImportService's
        // existing "Import Existing Section" pipeline unchanged) so the
        // block's content is captured instead of lost.
        $sectionHandles = [];
        $demoContent = [];
        $autoGeneratedSections = [];
        foreach ($blocks as $block) {
            $entryTypeHandle = $block->getType()->handle;
            $sectionHandle = $entryTypeToSection[$entryTypeHandle] ?? null;
            if (!$sectionHandle) {
                $sectionHandle = $this->autoGenerateSectionPackage($block->getType());
                if (!$sectionHandle) {
                    // Genuinely couldn't generate one (e.g. already imported
                    // under a different handle, or no capturable fields) -
                    // skip this block rather than fail the whole save.
                    continue;
                }
                $entryTypeToSection[$entryTypeHandle] = $sectionHandle;
                $autoGeneratedSections[] = $sectionHandle;
            }

            $sectionHandles[] = $sectionHandle;
            $demoContent[$sectionHandle] = $this->extractFieldValues($block, [], $packagePath);
        }

        if (empty($sectionHandles)) {
            throw new \Exception('No recognized Site7 Sections were found in this entry.');
        }

        [$requiresPatterns, $requiresSections] = $this->detectPatternReferences($sectionHandles);

        // Capture the source Entry's own custom fields (its Section/Entry Type field
        // layout) - everything except the Site7 Matrix field, which is captured above
        // via demoContent/requires instead. Structural identity (handles) only, per
        // the "DO NOT SAVE" rule - never the entry's own runtime ID/slug/title/etc.
        $entryFields = $this->extractFieldValues($entry, [$matrixHandle], $packagePath);

        $tags = array_values(array_filter(array_map('trim', explode(',', (string)($meta['tags'] ?? '')))));

        $manifest = [
            'schemaVersion' => '1',
            'handle' => $handle,
            'name' => $meta['name'],
            'type' => 'template',
            'version' => '1.0.0',
            'author' => Craft::$app->getUser()->getIdentity()?->friendlyName ?? 'Site7',
            'description' => $meta['description'] ?? '',
            'category' => $meta['category'] ?? null,
            'tags' => $tags,
            'sourceEntryType' => $entry->getType()->handle,
            'sourceSection' => $entry->getSection()?->handle,
            'sourceSectionType' => $entry->getSection()?->type,
            'requires' => array_filter([
                'patterns' => $requiresPatterns,
                'sections' => $requiresSections,
            ]),
            'demoContent' => $demoContent,
            'entryFields' => $entryFields,
            'dependencies' => [],
        ];

        file_put_contents($packagePath . '/manifest.json', json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        file_put_contents($packagePath . '/README.md', $this->buildReadme($meta['name'], $sectionHandles));

        FileHelper::createDirectory($packagePath . '/preview');
        file_put_contents($packagePath . '/preview/preview-data.yaml', Yaml::dump(['block' => $demoContent], 4));
        file_put_contents($packagePath . '/preview/preview.twig', $this->buildPreviewTwig($sectionHandles));

        /** @var UploadedFile|null $previewImage */
        $previewImage = $meta['previewImage'] ?? null;
        if ($previewImage instanceof UploadedFile && $previewImage->tempName) {
            copy($previewImage->tempName, $packagePath . '/preview/preview.png');
        }

        $packageManager = Site7Studio::getInstance()->packageManager;
        $packageManager->discoverPackages();
        $packageManager->installPackage($handle);
        $packageManager->enablePackage($handle);

        $record = $packageManager->getPackageByHandle($handle);
        if (!$record) {
            throw new \Exception('Template was generated but could not be registered.');
        }

        // Recorded so the capturing user can delete this specific Template later
        // without needing the broader Package Authoring permission - see
        // PackageActionController::actionDelete().
        $record->creatorId = Craft::$app->getUser()->getId();
        $record->save();

        return $record;
    }

    private function getMatrixFieldHandle(): ?string
    {
        $settings = Site7Studio::getInstance()->getSettings();
        if (!$settings->matrixFieldId) {
            return null;
        }
        $field = Craft::$app->getFields()->getFieldById($settings->matrixFieldId);
        return $field?->handle;
    }

    /**
     * Builds an [entryTypeHandle => sectionPackageHandle] map by scanning every
     * Section package's matrix.yaml, mirroring the same on-demand lookup already
     * performed (in the opposite direction) by PatternInsertionService and
     * PackageActionController::actionGetBrowserData.
     */
    private function buildEntryTypeToSectionMap(): array
    {
        $packageManager = Site7Studio::getInstance()->packageManager;
        $map = [];

        foreach ($packageManager->getAllPackages() as $pkg) {
            if (strtolower($pkg->type) !== 'section') {
                continue;
            }
            $path = $packageManager->getPackagePath($pkg->handle);
            if (!$path) {
                continue;
            }
            $matrixYamlPath = $path . '/matrix.yaml';
            if (!file_exists($matrixYamlPath)) {
                continue;
            }
            $matrixData = Yaml::parseFile($matrixYamlPath);
            $entryTypeHandle = $matrixData['blocks'][0]['handle'] ?? null;
            if ($entryTypeHandle) {
                $map[$entryTypeHandle] = $pkg->handle;
            }
        }

        return $map;
    }

    /**
     * Given a live Entry Type that isn't yet backed by any installed Section
     * package, generates one on the fly by delegating to
     * MatrixEntryTypeImportService::importFromEntryType() - the same,
     * unmodified pipeline "Import Existing Section" already uses, rather
     * than a second implementation of Entry-Type-to-Section-package
     * conversion. Never fails the caller's save: any exception (e.g. the
     * Entry Type was already imported under a source-uid guard collision, or
     * has no capturable fields) is caught and null returned so the block is
     * simply skipped, exactly as an unrecognized Entry Type already was
     * before this method existed.
     */
    private function autoGenerateSectionPackage(\craft\models\EntryType $entryType): ?string
    {
        try {
            $record = (new MatrixEntryTypeImportService())->importFromEntryType($entryType->id, [
                'name' => $entryType->name,
                'description' => "Auto-generated while importing a page that used the \"{$entryType->name}\" Entry Type as a Site7 block, but had no matching Section package yet.",
                // MatrixEntryTypeImportService::importFromEntryType() reads
                // $meta['category'] with a direct array access (not ??), so
                // an omitted key throws an ErrorException under Craft's
                // strict error handler - always pass it explicitly.
                'category' => null,
            ]);
            return $record->handle;
        } catch (\Throwable $e) {
            Craft::warning("Could not auto-generate a Section package for Entry Type '{$entryType->handle}': " . $e->getMessage(), __METHOD__);
            return null;
        }
    }

    /**
     * Reads a nested block's (or a top-level Entry's) custom field values into a
     * plain associative array. Section/entry fields are all PlainText today
     * (CraftResourceService's MVP scope), so a general field-type serializer isn't
     * needed - values are read as-is.
     *
     * $skipHandles excludes relational/non-scalar fields (e.g. the Site7 Matrix
     * field itself, when reading a top-level Entry) that would otherwise hit the
     * (string) cast below and fatal - ElementQueryInterface has no __toString().
     *
     * Beyond that, any other field value that isn't scalar/null (e.g. relation
     * queries, or third-party field value objects like ether/seo's SeoData,
     * which has no __toString()) is only cast if it's actually safely
     * stringable; otherwise it's omitted rather than fataling. Mirrors the
     * same guard already used by PageImportService::captureNativeFields().
     *
     * An Assets field's VALUE (not its definition - Assets fields are always
     * a Shared Resource, see ResourceClassifierService) is captured via
     * AssetCaptureHelper when $packagePath is available, so the selected
     * image(s) travel with the package instead of being silently dropped.
     */
    private function extractFieldValues(Entry $block, array $skipHandles = [], ?string $packagePath = null): array
    {
        $values = [];
        $layout = $block->getFieldLayout();
        if (!$layout) {
            return $values;
        }
        foreach ($layout->getCustomFields() as $field) {
            if (in_array($field->handle, $skipHandles, true)) {
                continue;
            }
            $value = $block->getFieldValue($field->handle);
            if ($field instanceof Assets) {
                $descriptor = AssetCaptureHelper::captureAssetField($value, $packagePath, $packagePath !== null);
                if ($descriptor !== null) {
                    $values[$field->handle] = $descriptor;
                }
                continue;
            }
            if ($value instanceof ElementQueryInterface) {
                // Entries/Categories/Tags/nested-Matrix relation fields (and any
                // other Assets-like relation not already handled above). These
                // resolve to a query object, not a value - and ElementQuery's own
                // __toString() deceptively returns its own class name rather than
                // throwing, so the naive method_exists('__toString') check below
                // would silently capture "craft\elements\db\ElementQuery" as
                // "content" instead of skipping it. Not something (string) can
                // meaningfully serialize, so it's omitted like other unserializable
                // objects.
                continue;
            }
            if (is_scalar($value) || $value === null) {
                $values[$field->handle] = $value;
            } elseif (is_object($value) && method_exists($value, '__toString')) {
                $values[$field->handle] = (string)$value;
            }
            // Non-stringable objects (relation queries, SEO data models, etc.)
            // are silently omitted rather than crashing the whole save - the
            // field simply isn't captured as static demo content.
        }
        return $values;
    }

    /**
     * Scans the ordered section-handle sequence for contiguous runs that exactly
     * match an existing Pattern's requires.sections, replacing each matched run with
     * a Pattern reference. Remaining sections are returned as bare Sections. This is
     * a best-effort reconstruction - true arbitrary interleaving of Patterns and
     * Sections isn't representable under Phase 9's existing (frozen) ordering model,
     * where all requires.patterns are expanded before any requires.sections.
     *
     * @return array{0: string[], 1: string[]} [requiresPatterns, requiresSections]
     */
    private function detectPatternReferences(array $sectionHandles): array
    {
        $packageManager = Site7Studio::getInstance()->packageManager;
        $patterns = array_filter($packageManager->getAllPackages(), fn($p) => strtolower($p->type) === 'pattern');

        $requiresPatterns = [];
        $requiresSections = [];
        $i = 0;
        $count = count($sectionHandles);

        while ($i < $count) {
            $matchedPattern = null;
            foreach ($patterns as $pattern) {
                $manifest = $pattern->getManifest();
                $required = $manifest?->requires['sections'] ?? [];
                $len = count($required);
                if ($len === 0 || $i + $len > $count) {
                    continue;
                }
                if (array_slice($sectionHandles, $i, $len) === $required) {
                    $matchedPattern = $pattern;
                    $i += $len;
                    break;
                }
            }

            if ($matchedPattern) {
                $requiresPatterns[] = $matchedPattern->handle;
            } else {
                $requiresSections[] = $sectionHandles[$i];
                $i++;
            }
        }

        return [$requiresPatterns, $requiresSections];
    }

    private function generateUniqueHandle(string $name): string
    {
        $base = StringHelper::toKebabCase($name);
        $handle = $base;
        $basePath = Craft::getAlias('@packages');
        $suffix = 2;
        while (is_dir($basePath . '/' . $handle)) {
            $handle = $base . '-' . $suffix;
            $suffix++;
        }
        return $handle;
    }

    private function buildReadme(string $name, array $sectionHandles): string
    {
        $list = implode("\n", array_map(fn($h) => "- {$h}", $sectionHandles));
        return "# {$name}\n\nGenerated from an existing page via \"Save as Template\".\n\nSection order:\n\n{$list}\n";
    }

    private function buildPreviewTwig(array $sectionHandles): string
    {
        $includes = implode("\n", array_map(
            fn($h) => "    {% include \"@packages/{$h}/template.twig\" with { block: block['{$h}']|default({}) } only %}",
            $sectionHandles
        ));
        return "<div class=\"site7-template-preview\">\n{$includes}\n</div>\n";
    }
}
