<?php

namespace site7\studio\services\import;

use Craft;
use craft\base\Component;
use site7\studio\records\PackageRecord;

/**
 * Converts a native Craft Section (Single/Channel/Structure) into Site7
 * Section packages - the "Import Existing Section" flow's Craft Section
 * source. A Site7 Section package is always exactly one Entry Type (per
 * matrix.yaml's blocks[0] convention - see TemplateGeneratorService::
 * buildEntryTypeToSectionMap()), so a Craft Section with multiple Entry
 * Types produces one package per selected Entry Type, each generated by the
 * same routine MatrixEntryTypeImportService uses - a Craft Section's Entry
 * Type is structurally identical to a "loose" one for import purposes.
 */
class CraftSectionImportService extends Component
{
    /**
     * @param int[] $entryTypeIds Entry Type ids belonging to the section to import.
     * @param array $meta {name, description?, category?, tags?, version?} - $meta['name'] is used
     *   as a base; each resulting package is named "{name} - {Entry Type name}" when more than
     *   one Entry Type is selected, and just $meta['name'] when only one is.
     * @return array{0: PackageRecord[], 1: string[]} [imported package records, per-entry-type skip reasons]
     * @throws \Exception if the Section can't be found, or none of its Entry Types could be imported.
     */
    public function importFromSection(int $sectionId, array $entryTypeIds, array $meta): array
    {
        $section = Craft::$app->getEntries()->getSectionById($sectionId);
        if (!$section) {
            throw new \Exception('Section not found.');
        }

        $sectionEntryTypeIds = array_map(fn($et) => $et->id, $section->getEntryTypes());
        $entryTypeIds = array_values(array_intersect($entryTypeIds, $sectionEntryTypeIds));
        if (empty($entryTypeIds)) {
            throw new \Exception('None of the selected Entry Types belong to this Section.');
        }

        $importer = new MatrixEntryTypeImportService();
        $records = [];
        $skipped = [];
        $multiple = count($entryTypeIds) > 1;

        foreach ($entryTypeIds as $entryTypeId) {
            $entryType = Craft::$app->getEntries()->getEntryTypeById($entryTypeId);
            $entryTypeMeta = $meta;
            if ($multiple && $entryType) {
                $entryTypeMeta['name'] = trim((string)($meta['name'] ?? $section->name)) . ' - ' . $entryType->name;
            }

            try {
                $record = $importer->importFromEntryType($entryTypeId, $entryTypeMeta);
            } catch (\Throwable $e) {
                $skipped[] = ($entryType?->name ?? "Entry Type #{$entryTypeId}") . ': ' . $e->getMessage();
                continue;
            }

            // Recorded here (rather than only inside MatrixEntryTypeImportService)
            // so the resulting Section package's provenance also identifies the
            // native Craft Section it came from, in addition to the Entry Type.
            $packagePath = \site7\studio\Site7Studio::getInstance()->packageManager->getPackagePath($record->handle);
            if ($packagePath && file_exists($packagePath . '/manifest.json')) {
                $manifestData = json_decode(file_get_contents($packagePath . '/manifest.json'), true) ?: [];
                $manifestData['importedFrom']['sourceType'] = 'craft-section';
                $manifestData['importedFrom']['sourceSectionId'] = $section->id;
                $manifestData['importedFrom']['sourceSectionHandle'] = $section->handle;
                file_put_contents($packagePath . '/manifest.json', json_encode($manifestData, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
            }

            $records[] = $record;
        }

        if (empty($records)) {
            throw new \Exception('None of the selected Entry Types could be imported: ' . implode('; ', $skipped));
        }

        return [$records, $skipped];
    }
}
